name: Acceptance tests
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
        python-version: [3.8]
    env:
        GIT_NAME: volto-blocks
        NAMESPACE: "@kitconcept"
        GIT_USER: 'kitconcept'
    steps:
      - name: Main checkout
        uses: actions/checkout@v2

      # node setup
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      # node install
      - name: Install dependencies
        run: yarn install

      - name: Install yo and @plone/generator-volto
        run: npm i -g yo @plone/generator-volto

      - name: Extract branch name
        run: echo "branch=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Setup addon testing environment
        run: npx -p @plone/scripts addon clone https://github.com/${{env.GIT_USER}}/${{env.GIT_NAME}}.git --branch ${{ steps.extract_branch.outputs.branch }}

      # Acceptance tests
      - name: Acceptance tests
        run: cd addon-testing-project && yarn cypress:ci:full

      # Upload Cypress screenshots
      - uses: actions/upload-artifact@v1
        name: Upload screenshots on failure
        if: failure()
        with:
          name: cypress-screenshots
          path: addon-testing-project/src/addons/volto-blocks/cypress/screenshots
      # Upload Cypress videos
      - uses: actions/upload-artifact@v1
        name: Upload cypress result videos
        if: always()
        with:
          name: cypress-videos
          path: addon-testing-project/src/addons/volto-blocks/cypress/videos
